apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: busy-dm
  namespace: default
  labels:
    app: busy-dm
spec:
  template:
    metadata:
      labels:
        name: busy-dm
    spec:
      nodeSelector:
        kubernetes.io/hostname: 'ip-172-20-53-35.ec2.internal'
      containers:
      - image: busybox
        command:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
