apiVersion: v1
data:
  you: only
  leave: once
kind: ConfigMap
metadata:
  name: omni
---
apiVersion: v1
kind: Pod
metadata:
  name: cfg-env
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: omni
  restartPolicy: Never
