apiVersion: v1
kind: Service
metadata:
  name: manual-svc-endpoint
spec:
  ports:
  - name: app
    port: 9855
    protocol: TCP
    targetPort: 9855
---
apiVersion: v1
kind: Endpoints
metadata:
  name: manual-svc-endpoint
subsets:
- addresses:
  - ip: 172.17.0.5
  ports:
  - name: app
    port: 9855
    protocol: TCP
