apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # port needed to create SRV records, SRV records have pod DNS name
  ports:
  - port: 80
    name: web
  # - port: 9443
  #   name: https
  # for headless service
  clusterIP: None
  # selector needed to create pods dns name
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        - name: scripts
          mountPath: /scripts_www
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
        volumeMounts:
        - name: scripts
          mountPath: /scripts_busybox
      volumes:
      - emptyDir: {}
        name: scripts
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
